refactor: update stack with component-rollup-config
ovh-ux/ng-ovh-input-password pull request #5
Opened 2019-02-04 16:27 UTC by cbourgois

## refactor: update stack with component-rollup-config

### Description of the Change

replace module name from 'ovh-ng-input-password' to 'ngOvhInputPassword'
BREAKING CHANGE: module is now named `ngOvhInputPassword`

4abcb44 — refactor: update stack with component-rollup-config

ref: 

### TODO : 

* [ ] rename repository to `ng-ovh-input-password`

/cc @jleveugle @frenautvh @antleblanc

2019-02-05 08:24 UTC, antleblanc requested changes

2019-02-05 08:24 UTC, antleblanc commented on .eslintrc.json
> +  "overrides": [{
According to the `README.md` file, these `overrides` aren't needed.

2019-02-05 08:24 UTC, antleblanc commented on .gitignore
> +dist
+`tools`

2019-02-05 08:24 UTC, antleblanc commented on src/index.less
> +@ovhNgInputPasswordPopoverBgColor: #f3f3f3;
Shouldn't be `kebabCase` instead?

2019-02-05 19:45 UTC, cbourgois commented on src/index.less
> +@ovhNgInputPasswordPopoverBgColor: #f3f3f3;
Done :)

2019-02-06 08:27 UTC, antleblanc requested changes

2019-02-06 08:27 UTC, antleblanc commented on .lintstagedrc.json
> +  "*.js": [
Missing `*.less`.

2019-02-06 08:27 UTC, antleblanc commented on package.json
> +    "lint:js": "eslint --quiet --fix --format=pretty src",
Missing `lint:css` as well.

2019-02-06 08:27 UTC, antleblanc commented on package.json
> +    "@ovh-ux/component-rollup-config": "5.0.0-beta.5",
```suggestion
    "@ovh-ux/component-rollup-config": "5.0.0-beta.6",
```

2019-02-06 08:27 UTC, antleblanc commented on src/controller.js
> +
extra empty line.

2019-02-06 08:27 UTC, antleblanc commented on src/translations/Messages_fr_FR.xml
> +<?xml version="1.0" encoding="utf-8"?>
Could we keep only XML file?

2019-02-06 08:27 UTC, antleblanc commented on src/toggle/index.js
> +// import './index.less';
Needed?

2019-02-07 10:26 UTC, cbourgois commented on package.json
> +    "@ovh-ux/component-rollup-config": "5.0.0-beta.5",
Bumped.

```suggestion
    "@ovh-ux/component-rollup-config": "5.0.0-beta.8",
```

2019-02-07 10:28 UTC, cbourgois commented on package.json
> +    "lint:js": "eslint --quiet --fix --format=pretty src",
added `lint:html` too.

2019-02-07 10:28 UTC, cbourgois commented on .lintstagedrc.json
> +  "*.js": [
`*.html` added too

2019-02-07 10:28 UTC, cbourgois commented on src/translations/Messages_fr_FR.xml
> +<?xml version="1.0" encoding="utf-8"?>
`json` files removed (and empty `en_GB` xml too)

2019-02-08 08:30 UTC, antleblanc approved these changes

2019-02-08 08:31 UTC, merged